name: "release"

on:
  push:
    tags:
      - "*"

jobs:
  run:
    runs-on: ubuntu-latest
    container: shivammathur/node:latest-i386
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Build release
      - run: npm i
      - run: npm run build
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/plg_system_aesirx_sso.zip"
          generateReleaseNotes: true